address: 0.0.0.0
port: 8001

static_dir: res/static
template_dir: res/templates
upload_dir: uploads

banners:
    - 1.png
    - 2.png
    - 3.png
    - 4.png

database_url: postgres://longboard:@localhost/longboard

filter_rules:
    - pattern: word\s?filter
      replace_with: language enhancer
    - pattern: big dick
      replace_with: sizable dongus
