.ad l
.TH longboard 8 2020-04-20
.SH NAME
longboard \- imageboard engine
.SH SYNOPSIS
.B longctl
[\fB-c\fR \fIconfig\fR] [\fB-x\fR \fIdir\fR] [\fB-h\fR] [\fB-V\fR] [\fICOMMAND\fR]
.br
.B longctl
[\fIOPTIONS\fR...] add-staff \fB-u\fR \fINAME\fR \fB-p\fR \fIPASS\fR
\fB-r\fR \fIROLE\fR
.br
.B longctl
[\fIOPTIONS\fR...] remove-staff \fB-u\fR \fINAME\fR
.SH DESCRIPTION
.B longctl
is a tool for managing a longboard instance.
.SH OPTIONS
.TP
.BR \-c ", " \-\-config " " \fIconfig\fR
The config file to load. Defaults to \fI/etc/longboard/config.yaml\fR.
.TP
.BR \-x ", " \-\-extension-dir " " \fIdir\fR
The directory to search for extensions.
.TP
.BR \-h ", " \-\-help
Show a help message.
.TP
.BR \-V ", " \-\-version
Show the program version.
.SS add-staff
Add a staff member.
.TP
.BR \-u ", " \-\-user " " \fINAME\fR
The name of the staff member to add.
.TP
.BR \-p ", " \-\-pass " " \fIPASS\fR
The new staff members's password.
.TP
.BR \-r ", " \-\-role " " \fIROLE\fR
The role of the new staff member. Can be one of janitor, moderator, or
administrator.
.SS remove-staff
Remove a staff member.
.TP
.BR \-u ", " \-\-user " " \fINAME\fR
The name of the staff member to remove.
.SH SEE ALSO
longboard(5), longboard(8)
