# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "longboard"
version = "0.1.0"
authors = ["set <set@hierophant.club>"]
edition = "2018"
default-run = "longboard"

[[bin]]
name = "lbinfo"
path = "src/bin/lbinfo.rs"

[[bin]]
name = "longboard"
path = "src/bin/longboard.rs"

[dependencies]
chrono = "0.4"
derive_more = "0.99"
diesel = { version = "1.4", features = ["postgres", "chrono"] }
handlebars = "3.0"
log = "0.4"
pretty_env_logger = "0.3"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
