address: 0.0.0.0
port: 8000

resource_dir: res
upload_dir: uploads

database_url: postgres://longboard:@localhost/longboard

names: contrib/config/names.txt
notice: contrib/config/notice.md

filter_rules:
    - pattern: word\s?filter
      replace_with: language enhancer
    - pattern: big dick
      replace_with: sizable dongus

pages:
    - Rules

styles:
    - dark
    - light
