pages_dir: contrib/config/pages
names: contrib/config/names.txt
notice: contrib/config/notice.md

filter_rules:
    - pattern: word\s?filter
      replace_with: language enhancer
    - pattern: big dick
      replace_with: sizable dongus

styles:
    - dark
    - light
