address: 0.0.0.0
port: 8000

resource_dir: res
upload_dir: uploads

database_url: postgres://longboard:@localhost/longboard

names_path: contrib/config/names.txt

filter_rules:
    - pattern: word\s?filter
      replace_with: language enhancer
    - pattern: big dick
      replace_with: sizable dongus
