# Configuration file for longboard.

# The address that the server binds to.
address: 0.0.0.0

# The port that the server binds to.
port: 80

# How to connect to the database.
database_uri: postgres://longboard:@localhost/longboard

# Where the resources (templates, css, javascript, ...) are stored.
resource_dir: /var/lib/longboard

# Where the user-uploaded files are stored.
upload_dir: /var/lib/longboard/uploads

# Where the staff-added pages are stored.
pages_dir: /etc/longboard/pages

# List of names to use for anonymous posters.
names: /etc/longboard/names.txt

# A notice message that will be displayed at the top of each board/thread.
notice: /etc/longboard/notice.md

# Rules to filter posts with. The pattern is parsed as a regex.
# See https://docs.rs/regex/1.3.7/regex/#syntax for regex syntax.
filter_rules:
    - pattern: word\s?filter
      replace_with: language enhancer

# Stylesheets to use. Any style you add here will be selectable by your users
# to use, provided it exists in $RESOURCE_DIR/styles/.
styles:
    - light
    - dark

# The maximum size for user-uploaded files.
file_size_limit: 2M
